apiVersion: v1
kind: Pod
metadata:
  name: guestbook-proxy
spec:
  containers:
  #- name: proxy-udp
  #  image: gcr.io/google_containers/proxy-to-service:v2
  #  args: [ "udp", "53", "kube-dns.default", "1" ]
  #  ports:
  #  - name: udp
  #    protocol: UDP
  #    containerPort: 53
  #    hostPort: 53
  - name: proxy-tcp
    image: gcr.io/google_containers/proxy-to-service:v2
    args: [ "tcp", "53", "kube-dns.default" ]
    ports:
    - name: tcp
      protocol: TCP
      containerPort: 80
      hostPort: 80
