---
#- include_vars: ansible_aws_variables.yml

- name: Weave on AWS with Ansible Setup 
  hosts: localhost
  connection: local
  tags: provisioning
  vars_files: 
    - ansible_aws_variables.yml
  vars:
    ssh_key: weavedemo
    num_nodes: 2
    security_group_name: weavedemo
    instance_type: m1.small

  roles:
    - common
    - ubuntuinstall

  tasks: 
  - name: Add new instance to host group
    add_host: name="{{ item.public_ip }}" groupname=launched 
    with_items: ec2.instances

- name: Install Weave and Docker on Hosts
  tags: dockerinstall
  hosts: launched 
  sudo: yes
  remote_user: ubuntu
  vars:
    ansible_ssh_private_key_file: "~/.ssh/id_rsa_{{ ssh_key }}"
    ssh_key: weavedemo
  roles: 
  - dockerinstall
  - weaveinstall
